apiVersion: v1
kind: ConfigMap
metadata:
  name: crudapp-configmap
data:
  application.properties: |
    spring.data.mongodb.username=${MONGO_INITDB_ROOT_USERNAME}
    spring.data.mongodb.password=${MONGO_INITDB_ROOT_PASSWORD}
    spring.data.mongodb.host=mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapp
  labels:
    app: crudapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudapp
  template:
    metadata:
      labels:
        app: crudapp
    spec:
      containers:
        - name: crudapp
          image: mp7373/crudapp
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 8080
          env:
            - name: --spring.config.location
              value: "/etc/config/"
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-user-pass
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-user-pass
                  key: password
          volumeMounts:
            - name: crudapp-configmap
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: crudapp-configmap
          configMap:
            name: crudapp-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: crudapp
spec:
  selector:
    app: crudapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crudapp
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/issuer: "letsencrypt"
spec:
  rules:
  - host: "kiryuin-satsuki-cluster.martinpayne.dev"
    http:
        paths:
        - path: /crudapp(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: crudapp
              port:
                number: 80
  tls:
  - hosts:
    - kiryuin-satsuki-cluster.martinpayne.dev
    secretName: crudapp-tls